# Generated by Django 5.2.3 on 2025-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_article_options_remove_article_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
